### ISSUE TITLE
Will not minimize an Oracle VirtualBox VM

### ISSUE THREAD

**Issue by bommerts** [benbuck/rbtray#18] opened 2018-12-27 22:25 UTC
When trying to minimize a VM running from Oracle VirtualBox, the default "Restore, Move, Size..." etc dialog box pops up.

Works great on everything else I've tested.

**Comment by benbuck** [comment] 2018-12-29 03:15
Hi @bommerts,

This seems like a duplicate of issue #4, have you tried using the Win+Alt+Down keyboard shortcut method to minimize VirtualBox?

Benbuck

**Comment by benbuck** [comment] 2019-01-04 05:51
Hi @bommerts,

I'm closing this under the assumption that the keyboard shortcut will work for you, please let me know if not.

Benbuck

**Closed by benbuck** 2019-01-04 05:51 UTC
