### ISSUE TITLE
System Tray / Taskbar messed up after last Windows 10 update

### ISSUE THREAD

**Issue by zbhavyai** [benbuck/rbtray#60] opened 2021-06-03 17:08 UTC
Experiencing issue with RBTray after last update in Windows 10. After putting any windows in the system tray, all the icons - battery, network, clock - disappears, only to be visible when taskbar is expanded. Also shows normal window icons are shown to be superimposed on the system tray in an unorderly fashion. Issue is resolved when RBTray is forcibly quit.

```
Edition	        Windows 10 Home Single Language
Version	        21H1
Installed on    ‎02-‎May-‎2021
OS build        19043.1023
Experience      Windows Feature Experience Pack 120.2212.2020.0
```

**Comment by benbuck** [comment] 2021-06-08 22:38
Hi @zbhavyai,

I'm going to mark this as a duplicate of #58, please let me know if you think it's different.

Thanks,
Benbuck

**Closed by benbuck** 2021-06-08 22:38 UTC
Labels: duplicate

**Comment by zbhavyai** [comment] 2021-06-09 11:20
Sure! @benbuck

Thanks
