### ISSUE TITLE
RBTray causes framerates to tank in some(?) games.

### ISSUE THREAD

**Issue by Cattywampus-** [benbuck/rbtray#17] opened 2018-12-24 17:07 UTC
Hi

So love your app.  Lightweight low impact etc... problem is there seems to be some issues with it and games.  The only game I have had this particular issue on so far is PUBG, but I don't have many games to try it on so I very much suspect there are other games that are affected.   I believe I didn't have the issue with Fallout 76. 

Basically with RBTray running in the background, as soon as you move the mouse in the game, the framerates tank. Soon you stop moving mouse, everything reverts to normal. 

Another 'feature' of this bug is that when you hold the mouse button down and move the mouse, the stuttering doesn't occur.

I tried updating Riva Tuner to the latest version as per this thread: https://github.com/benbuck/rbtray/issues/13 but the issue is still present.  Problem still occurs when you remove Riva Tuner from the equation.

Would be great to find a resolution.  Thanks.

**Comment by benbuck** [comment] 2018-12-24 19:49
Hi @Cattywampus-,

I agree, it would be nice to find a resolution to this, but I don't really have any idea what the problem might be, and at least in #13 I wasn't able to reproduce this.

Do you have the time/expertise to try narrow this down and or diagnose it yourself, or to provide a reliable way for me to reproduce it?

Thanks,
Benbuck

**Comment by Cattywampus-** [comment] 2018-12-24 20:00
Hi Benbuck,

I don't have the expertise unfortunately. Not that talented :)  The only way I can suggest a way to reproduce this is to load PUBG and RBTray (if you even have PUBG that is).  The issue is apparent immediately as the lobby/menu screen is rendering the game as it does when you're actually playing it. 

Something I forgot to mention, when loading PUBG with RBTray running, BattleEye, PUBG's anti-cheating doodad throws a message up saying this:
`19:56:06: Note: File blocks can be ignored if they don't cause problems with the game.
19:56:06: [INFO] Blocked loading of file: "F:\Dropbox\Apps\RBTray 4.8\RBHook.dll".`

The game will run normally with it loaded albeit with the frame rate stuttering. 

I really do not know what else to say.  Am happy to run any tests you may want to run though.  Cheers.

**Comment by benbuck** [comment] 2018-12-26 22:59
Hi @Cattywampus-,

Unfortunately I don't own PUBG, but that part about the anti-cheating mechanism blocking the load of RBHook.dll is very suspicious. Is there a way to disable that mechanism (maybe in training mode)?

This seems to be confirmed here:
https://steamcommunity.com/app/578080/discussions/1/1727575977541107382/

I'm not sure there's anything I can do about this, but if I think of anything I'll follow up here.

Benbuck

**Comment by benbuck** [comment] 2018-12-26 23:01
There's another mention of the problem here:
https://www.reddit.com/r/PUBATTLEGROUNDS/comments/66vsik/battleye_doesnt_like_rivatuner/

Benbuck

**Comment by benbuck** [comment] 2020-03-23 16:21
Hi @Cattywampus-,

I just released version 4.11, which has a new feature from @OndrejPetrzilka to disable the RBTray mouse hook. Could you please try running with `--no-hook` on the command line to see if that helps with this issue?

Thanks,
Benbuck

**Comment by benbuck** [comment] 2020-05-14 00:36
Hi @Cattywampus-,

I'm going to close this issue, please let me know if the `--no-hook` option doesn't work for you.

Thanks,
Benbuck

**Closed by benbuck** 2020-05-14 00:36 UTC
Labels: can't reproduce
