### ISSUE TITLE
Taskbar messed up since last Windows update

### ISSUE THREAD

**Issue by dot-i** [benbuck/rbtray#58] opened 2021-05-26 14:21 UTC
Seems some change in Windows broke RBTray. The tray area of the taskbar get totally messed up, as if it thinks the screen is wider than it really is on the one hand, and with garbage icons on top as an additional problem 😱 

Edition	Windows 10 Pro
Version	21H1
OS build	19043.1023
Experience	Windows Feature Experience Pack 120.2212.2020.0

Hope it's reproducable (and easily fixable).

**Comment by benbuck** [comment] 2021-06-08 22:40
Hi @dot-i,

I am updated to 10.0.19043, and am not experiencing any problems. You aren't the only one to have this issue (see #60), but I'm not sure what I can do about it right now. If you are able to discover any more information that might help me reproduce it, please let me know.

Thanks,
Benbuck

**Comment by zbhavyai** [comment] 2021-06-09 21:22
@benbuck I was wondering, are there any logs generated by RBtray that I could share with you which might help you with more information?

**Comment by retry-the-user** [comment] 2021-06-10 00:14
I just upgraded windoze 10 with the latest KB, which broke RBTray (the older, original one).  I was happy to find this fork which fixed my problems.  I did have my entire system tray disappear on me once, but after fixing that (toggle a toolbar on the taskbar on, then off again like the address bar), it seems stable.  With the original RBTray, everytime I tried to maximize Thunderbird, the whole thing disappeared every single time.

So thanks for keeping this incredibly useful utility alive.

**Comment by benbuck** [comment] 2021-06-10 00:38
> @benbuck I was wondering, are there any logs generated by RBtray that I could share with you which might help you with more information?

Hi @zbhavyai,

No unfortunately RBTray doesn't have any way to log any debug information at all.

Benbuck

**Comment by benbuck** [comment] 2021-06-10 00:38
Hi @retry-the-user,

Thanks for the comment, glad to hear it's working for you.

Benbuck

**Comment by benbuck** [comment] 2021-06-10 00:39
@dot-i  / @zbhavyai, can you please let me know which version of RBTray you are using?

Thanks,
Benbuck

**Comment by zbhavyai** [comment] 2021-06-10 10:28
@benbuck I am using RBTray 4.11.

Here's the about screenshot - [https://github.com/zbhavyai/test-share/blob/main/rbtray_version.png?raw=true](https://github.com/zbhavyai/test-share/blob/main/rbtray_version.png?raw=true)

**Comment by simondforrester** [comment] 2021-06-10 10:55
I haven't had time to extensively test this, but I was suffering the bug too. I dabbled with a few things, and it appears to be caused by having a Settings > Display > Scale and layout > change the size of... setting other than 100%. If you set it to, say, 150% and open the Start menu, the task tray/clock/notification problem appears.

So not a problem for most, but more prevalent in Surface-style laptops which have a higher resolution than any sane person would want to work at!

As an aside, nice work maintaining RBTray - it's an invaluable tool ❤️

**Comment by dylan1114** [comment] 2021-06-10 13:05
> I haven't had time to extensively test this, but I was suffering the bug too. I dabbled with a few things, and it appears to be caused by having a Settings > Display > Scale and layout > change the size of... setting other than 100%. If you set it to, say, 150% and open the Start menu, the task tray/clock/notification problem appears.
> 
> So not a problem for most, but more prevalent in Surface-style laptops which have a higher resolution than any sane person would want to work at!
> 
> As an aside, nice work maintaining RBTray - it's an invaluable tool ❤️

I can confirm this.👍 The problem happens when your **Scale and layout** under **Display** settings is something other than 100%. I use a compact laptop with a high resolution screen so it's on 125% normally. It breaks RBTray and that's how I got here in first place. If I set it back to 100% RBTray works fine.

So it can be replicated by trying to use RBTray with the setting on 125%.
Thank you so much for keeping this software updated @benbuck , it would be great if you can fix it for users with these settings.

**Comment by benbuck** [comment] 2021-06-10 14:47
Hi @simondforrester and @dylan1114,

That's good information, but unfortunately I still haven't been able to reproduce it on my desktop machine with 3440x1440 resolution and 125% scaling. Could there maybe be some other factor I'm missing?

Thanks,
Benbuck

**Comment by simondforrester** [comment] 2021-06-10 14:58
FWIW, I'm on a Surface Go, 1800x1200, 150% scaling. I've tried it across a few machines, and it's the scaling issue every time for me - it's the only thing I can find that triggers it.

**Comment by dylan1114** [comment] 2021-06-10 15:09
Perhaps it doesn't occur on resolutions that high? The laptop I have it on is 1920x1080.

**Comment by retry-the-user** [comment] 2021-06-11 05:31
I'm using 125% scaling on a 1920x1080 laptop.  It's not happening for me in a consistent way at all. Something triggered it once today, and I corrected it as I described above.  The only thing I use RBTray for is to minimize Thunderbird -- it's the only program I leave running that can't minimize to the tray on its own. 

Other things I've done or am doing that are peculiar: I completely disabled the new News feature through a registry key edit.  I use the old-fashioned taskbar buttons (shorter height with text), and I do not combine taskbar buttons.  Most of the newfangled windows 10 taskbar options are turned off.  Also I am running Open Shell Menu -- the continuation/fork of Classic Shell Menu.

**Comment by retry-the-user** [comment] 2021-06-11 07:47
Whelp, now it's blanking out the systray everytime I minimize or restore thunderbird.  I have no idea what changed just now. As an experiment, I set scaling to 100%.  That *DID* stop the blanking.  Restoring to 125%, it blanks out consistently now.  I probably will have to reboot to stop it, but I'll mess about with some other things first.

**Comment by retry-the-user** [comment] 2021-06-11 08:09
Killing and restarting explorer.exe did NOT fix the problem.

**Comment by retry-the-user** [comment] 2021-06-11 18:11
Alright that only worked once. The problem returned and quitting and restarting thunderbird didn't fix it.  I also was able to cause the problem with chrome.  Based on how inconsistent and hard to reproduce/trigger this bug is, and since it wasn't a problem before Windows' latest update patch, I have to point the finger at Microsoft here.  They obviously broke something they are unlikely to fix.  In the end of all my trial and err, one thing I did that consistently made the systray remain there was to enable the Address toolbar.  No other toolbar fixed the problem or prevented it from happening in the first place. But who wants that ugly, large, and useless toolbar on their taskbar all the time?

**Comment by benbuck** [comment] 2021-06-13 22:58
I was able to reproduce this by setting the text scaling to 150%, then restarting, and then minimizing a window with RBTray. Additionally, I was able to fix the problem by toggling Taskbar Settings->"Use small taskbar buttons". Looking at the RBTray code, I can't see anything I could be doing to cause this, or anything I could do differently to avoid it. Based on this, my guess is that this is a regression (bug) in the latest version of Windows. Please let me know if you find any new information.

Thanks,
Benbuck

**Comment by dot-i** [comment] 2021-06-17 07:55
I think this is related to a taskbar update and more specifically the new "News and interests" feature. When I keep this turned on it seems RBTray works just fine, when I turn it off the problems start.

So it's quite possible there's indeed nothing in the actual RBTray code that is wrong, and that this is just a subtle bug Microsoft introduced themselves.

**Comment by zbhavyai** [comment] 2021-06-17 12:10
@dot-i Good catch! Looks like, for the time being, I need to keep "News and interests" turned on in my taskbar just to make sure RBTray works fine.

**Comment by benbuck** [comment] 2021-06-17 22:45
Thanks everyone for the help investigating this. Based on the conclusion that this is a (very edge case) bug in Windows, I'm closing this as "Won't Fix", but please let me know if there is any new information that might change this conclusion.

Thanks,
Benbuck

**Closed by benbuck** 2021-06-17 22:45 UTC
Labels: wontfix
