### ISSUE TITLE
[Feature-Request] Have a persistent system tray icon for specific apps.

### ISSUE THREAD

**Issue by NightmareWyrm** [benbuck/rbtray#84] opened 2022-06-29 14:40 UTC
Have a way to configure certain apps to always minimize to tray. Whether we right click or left click minimized button or click the close the button.
To close the program we have to close it from the system tray icon.
This feature is useful for apps that are expected to always run in the background such as messenger apps, discord, and file synchronization software.
It will be easy for users of these programs to use them as they will do with similar apps that have this behavior rather than right-clicking it to minimize every time.
Thanks, I hope you find this suggestion useful.

**Comment by benbuck** [comment] 2022-07-06 06:59
Hi @NightmareWyrm,

If I'm understanding correctly, this looks like a duplicate of issue #44 so I'm closing this issue, but I invite you to submit a pull request for that issue if you like.

Thanks,
Benbuck

**Closed by benbuck** 2022-07-06 06:59 UTC
